# Generated by Django 5.1.4 on 2024-12-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('profissional', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('projeto', models.CharField(blank=True, max_length=255, null=True)),
                ('atividade_nome', models.CharField(max_length=255)),
                ('subatividade_nome', models.CharField(max_length=255)),
                ('horas_vendidas', models.IntegerField(default=0)),
                ('horas_adicionais', models.IntegerField(default=0)),
                ('hora_entrada', models.IntegerField(default=0)),
                ('hora_saida', models.IntegerField(default=0)),
                ('desc_atividade', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
