# Generated by Django 5.1.4 on 2024-12-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('id_company', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('id_project', models.CharField(blank=True, max_length=255, null=True)),
                ('id_user', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subactivity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hour_in', models.TimeField(blank=True, null=True)),
                ('hour_out', models.TimeField(blank=True, null=True)),
                ('desc_activity', models.TextField(blank=True, null=True)),
                ('hours_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('value_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('value_lanch', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('value_dinner', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('value_park', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('toll_i', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('toll_v', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('km_i', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('km_v', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('value_activity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('type_act', models.CharField(blank=True, max_length=255, null=True)),
                ('hour_sale', models.TimeField(blank=True, null=True)),
                ('hour_sale_total', models.TimeField(blank=True, null=True)),
                ('hour_total_act', models.TimeField(blank=True, null=True)),
                ('hour_add', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hour_act', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
    ]
